In [1]:
import numpy as np

In [2]:
A = np.array([
  [1, -1, 2],
  [3, 2, 2],
  [4, 1, 2]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
# 전치 행렬
A_transpose = np.transpose(A)
A_transpose = A.T
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [5]:
# 단위 행렬
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# 역행렬
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [7]:
A @ A_inverse

array([[ 1.00000000e+00,  4.44089210e-16, -1.11022302e-15],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])