In [1]:
import numpy as np

In [3]:
A = np.array([
  [1, -1, 2],
  [3, 2, 2],
  [4, 1, 2]
])

B = np.random.rand(3, 3)

In [5]:
A, B

(array([[ 1, -1,  2],
        [ 3,  2,  2],
        [ 4,  1,  2]]),
 array([[0.64666224, 0.42784276, 0.39636295],
        [0.60232116, 0.60897701, 0.42580826],
        [0.90456771, 0.82403619, 0.06574215]]))

In [6]:
A + B

array([[ 1.64666224, -0.57215724,  2.39636295],
       [ 3.60232116,  2.60897701,  2.42580826],
       [ 4.90456771,  1.82403619,  2.06574215]])

In [7]:
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [8]:
np.dot(A, B)

array([[1.85347651, 1.46693813, 0.10203899],
       [4.95376445, 4.14955469, 2.17218969],
       [4.99810553, 3.96842044, 2.14274438]])

In [9]:
A @ B

array([[1.85347651, 1.46693813, 0.10203899],
       [4.95376445, 4.14955469, 2.17218969],
       [4.99810553, 3.96842044, 2.14274438]])

In [10]:
A @ B + (A + 2 * B)

array([[ 4.14680098,  1.32262365,  2.8947649 ],
       [ 9.15840676,  7.36750871,  5.02380621],
       [10.80724095,  6.61649282,  4.27422868]])