In [1]:
import numpy as np

In [3]:
A = np.array([
  [1, 1, 2],
  [3, 2, 2],
  [4, 1, 2],
  [7, 5 ,6]
])

A

array([[1, 1, 2],
       [3, 2, 2],
       [4, 1, 2],
       [7, 5, 6]])

In [4]:
B = np.array([
  [0, 1],
  [-1, 3],
  [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [5]:
C = np.random.rand(3, 5)

C

array([[0.58101344, 0.4585477 , 0.37084441, 0.04929961, 0.9957384 ],
       [0.51219635, 0.76927003, 0.10739258, 0.66539712, 0.77749097],
       [0.2963801 , 0.82153014, 0.84723354, 0.75997599, 0.30104004]])

In [6]:
D = np.zeros((2, 4))

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
A[0][2]

2